### ISSUE TITLE
Github webhook signature verification susceptible to timing attacks

### ISSUE THREAD

**Issue by ecneladis** [SFTtech/kevin#1]
https://github.com/SFTtech/kevin/blob/3175df8b4d86f3f7ce570cd2358b63cdb25b547d/kevin/service/github.py#L38

Please use function performing constant time comparison like [hmac.compare_digest](https://docs.python.org/3/library/hmac.html#hmac.compare_digest).

**Comment by TheJJ** [comment]
Thanks :)
