### ISSUE TITLE
Discussion: how to handle unknown PR actions

### ISSUE THREAD

**Issue by zuntrax** [SFTtech/kevin#28]
GitHub has added new actions to the webhook api. We currently `raise` a `ValueError` when we get unknown actions, which results in a traceback in the log and errors in the GitHub webhook overview:
```
Traceback (most recent call last):
  File "/home/kevin/kevin/kevin/service/github.py", line 265, in post
    self.handle_pull_request(project, json_data)
  File "/home/kevin/kevin/kevin/service/github.py", line 331, in handle_pull_request
    raise ValueError("unknown pull_request action '%s'" % action)
ValueError: unknown pull_request action 'edited'
```
We probably should handle this more gracefully.

**Comment by TheJJ** [comment]
All known actions should be handled and logged without a traceback. Should be easy to add.
