### ISSUE TITLE
Naming Ideas

### ISSUE THREAD

**Issue by oberien** [SFTtech/kevin#9]
Here is a list of used / suggested names with their usage if applicable:
- [x] Kevin (Controller, trigger/action manager)
- [x] Falk (VM manager)
- [x] Chantal (In-VM runner)
- [x] Mandy (Webinterface)
- [ ] Rolf (CLI)
- [ ] Cindy
- [ ] Jacqueline
- [ ] Horst

**Comment by TheJJ** [comment]
I don't think we don't need more components for now. We'll come back here otherwise.
